config/routes.rb
Rails.application.routes.draw do
  root to: 'home#index'
  get 'productslisting', to: 'home#productslisting'
  get 'orderslisting', to: 'home#orderslisting'
  mount ShopifyApp::Engine, at: '/'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/product.rb
class Product < ApplicationRecord
end

app/models/shop.rb
# frozen_string_literal: true
class Shop < ActiveRecord::Base
  include ShopifyApp::ShopSessionStorage

  def api_version
    ShopifyApp.configuration.api_version
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/authenticated_controller.rb
# frozen_string_literal: true

class AuthenticatedController < ApplicationController
  include ShopifyApp::Authenticated
end

app/controllers/home_controller.rb
# frozen_string_literal: true

class HomeController < AuthenticatedController
  def index
    @products = ShopifyAPI::Product.find(:all, params: { limit: 10, page_info: params[:page_info] })
    @webhooks = ShopifyAPI::Webhook.find(:all)
  end

  def productslisting
    @productslist = ShopifyAPI::Product.find(:all, params: { limit: 10, page_info: params[:page_info] })
    # add_products(@productslist)
  end

  def orderslisting
    @orderslist = ShopifyAPI::Order.find(:all, params: { limit: 2, page_info: params[:page_info] })
  end

  # def add_products(products)
  #   products.each do |product|
  #     db_products = Product.new
  #     db_products.title = product.title
  #     db_products.title = product.title

  #   end
  # end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/home/index.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <link
      rel="stylesheet"
      href="https://unpkg.com/@shopify/polaris@4.25.0/styles.min.css"
      />
    </head>
    <body>
      <h2>Products</h2>
      <ul>
        <% @products.each do |product| %>
          <li><%= link_to product.title, "https://#{@current_shopify_session.domain}/admin/products/#{product.id}", target: "_top" %></li>
        <% end %>
      </ul>
      <%= link_to "List all products", productslisting_path %>
      <%= link_to "List all orders", orderslisting_path %>
      <ul>
      </ul>
      <hr>
      <h2>Webhooks</h2>
      <% if @webhooks.present? %>
        <ul>
          <% @webhooks.each do |webhook| %>
            <li><%= webhook.topic %> : <%= webhook.address %></li>
          <% end %>
        </ul>
      <% else %>
        <p>This app has not created any webhooks for this Shop. Add webhooks to your ShopifyApp initializer if you need webhooks</p>
      <% end %>
    </body>
  </html>

app/views/home/orderslisting.html.erb
<head>
  <style type="text/css">
    table,th,td {border: 1px solid black;}
    thead {background: #9370DB; color: black; }
    tbody {background: #fff; color: black; }
    table {margin: auto; width: 100%;border-collapse: collapse;}
    th,td {padding:10px; text-align: center; font-size: 15px;}
    .links,tr:hover {background:  	#8A2BE2; color:#fff;}
  </style>
  <style>
    #links_to {
       text-decoration: none;
       display: inline-block;
       padding: 10px;
       font-size: 15px;
       width: 20px;
       text-align: center;
    }
    .back:hover {
       background-color: #ddd;
       color: black;
    }
    .next:hover {
       background-color: rgb(121, 37, 133);
       color: white;
    }
    .back {
       border-radius: 50%;
       background-color: #acacac;
       color: black;
    }
    .next {
       border-radius: 50%;
       background-color: rgb(68, 30, 112);
       color: white;
    }
  </style>
</head>
<h2><center>Orders</center></h2>
<div>
  <table class="index_table">
    <thead id="head">
      <tr>
        <th>Name</th>
        <th>Order Number </th>
        <th>Note</th>
        <th>Note</th>
        <th>financial_status </th>
        <th>Total Price</th>
      </tr>
    </thead>
    <tbody id="ajax">
      <% @orderslist.each do |order| %>
        <tr>
          <td><%= order.name %></td>
          <td><%= order.order_number  %></td>
          <td><%= order.customer.first_name %></td>
          <td><%= order.note %></td>
          <td><%= order.financial_status   %></td>
          <td><%= order.total_price  %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
  <br>
  <br>
  <center>
    <% if !@orderslist.previous_page_info.nil? %>
      <%= link_to "<<", orderslisting_path(page_info: @orderslist.previous_page_info), id: "links_to", class: "back" %>
    <% end %>
    <% if !@orderslist.next_page_info.nil? %>
      <%= link_to ">>", orderslisting_path(page_info: @orderslist.next_page_info), id: "links_to", class: "next" %><br>
    <% end %>
  </center>

app/views/home/productslisting.html.erb
<h1>Listing Products</h1>
<table>
  <tr>
    <th>Title</th>
    <th>Vendor</th>
  </tr>
  <% @productslist.each do |product| %>
    <tr>
      <td><%= product.title %></td>
      <td><%= product.vendor %></td>
    </tr>
  <% end %>
</table>

app/views/layouts/_flash_messages.html.erb
<% content_for :javascript do %>
  <%= content_tag(:div, nil, id: 'shopify-app-flash', data: { flash: { notice: flash[:notice], error: flash[:error] } }) %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Summerfashions</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/layouts/embedded_app.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <% application_name = ShopifyApp.configuration.application_name %>
    <title><%= application_name %></title>
    <%= stylesheet_link_tag 'application' %>
    <% if ShopifyApp.use_webpacker? %>
      <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <% else %>
      <%= javascript_include_tag 'application', "data-turbolinks-track" => true %>
    <% end %>
    <%= csrf_meta_tags %>
  </head>

  <body>
    <div class="app-wrapper">
      <div class="app-content">
        <main role="main">
          <%= yield %>
        </main>
      </div>
    </div>

    <%= render 'layouts/flash_messages' %>

    <script src="https://unpkg.com/@shopify/app-bridge"></script>

    <%= content_tag(:div, nil, id: 'shopify-app-init', data: {
      api_key: ShopifyApp.configuration.api_key,
      shop_origin: @shop_origin || (@current_shopify_session.domain if @current_shopify_session),
      debug: Rails.env.development?
    } ) %>

    <% if content_for?(:javascript) %>
      <div id="ContentForJavascript" data-turbolinks-temporary>
        <%= yield :javascript %>
      </div>
    <% end %>
  </body>
</html>